# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build & test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  ARTIFACT_NAME: gogitfs-binary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o . ./...

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./gogitfs
        retention-days: 1

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run tests
      run: go test -v ./...

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "test/requirements.txt"

    - name: Test helper code
      run: python -m pytest -v test/repo_tests

    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./gogitfs

    - name: Run integration tests
      run: python -m pytest -v test/gogitfs_tests
      env:
        GOGITFS_BINARY: ./gogitfs
